platform:
  name: game-lab
  environment: production
  baseDomain: phobosandeimos.com

modules:
  web:
    enabled: true
    subdomain: games
    hostname: ""
  api:
    enabled: false
    subdomain: api
    hostname: ""
  mcp:
    enabled: false
    subdomain: mcp
    hostname: ""
  observability:
    enabled: false
    subdomain: grafana
    hostname: ""

ingress:
  enabled: true
  className: traefik
  tls:
    enabled: true
    clusterIssuer: letsencrypt-prod
